version: '2'

services:
  site:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "4567:4567"
    command: >
      bash -c "bundle exec middleman build --verbose && 
               bundle exec middleman server"
    volumes:
      - ./:/code
